# Generated by Django 4.2.5 on 2023-09-15 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Executions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='WorkerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.role')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter', models.TextField()),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.role')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daydate', models.DateField()),
                ('rol', models.CharField(default='', max_length=100)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('worker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule.worker')),
            ],
            options={
                'unique_together': {('worker', 'daydate', 'rol')},
            },
        ),
    ]
